# Generated by Django 4.1.1 on 2022-11-22 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('is_watched', models.BooleanField(default=False)),
                ('rate', models.PositiveIntegerField(blank=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
